---
# we use docker as plateform
driver:
  name: vagrant

# Ansible will be our provisioner
provisioner:
  name: ansible_playbook
  hosts: localhost
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_omnibus: false
  idempotency_test: true

# We use Inspec as testing framework
verifier:
  name: inspec
  inspec_tests:
    - path: tests/inspec

# Build platforms
platforms:
  # Standard Linux
  - name: centos-7
  - name: centos-6
  - name: fedora-28
  - name: fedora-27
  - name: fedora-26
  - name: ubuntu-18.04
  - name: ubuntu-17.10
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-9
  - name: debian-8
  - name: debian-7
  - name: oraclelinux-7
    driver:
      box: bento/oracle-7
  - name: oraclelinux-6
    driver:
      box: bento/oracle-6

  # Archlinux
  - name: archlinux-rolling
    driver:
      box: archlinux/archlinux
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_archlinux_target.rb

  # Gentoo
  - name: gentoo
    driver:
      box: generic/gentoo
      customize:
        memory: 2048
        cpus: 4
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_gentoo_target.rb

  # FreeBSD
  - name: freebsd-11.2
    driver:
      box: bento/freebsd-11.2
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_freebsd_target.rb
  - name: freebsd-10.4
    driver:
      box: bento/freebsd-10.4
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_freebsd_target.rb
  - name: freebsd-10.3
    driver:
      box: bento/freebsd-10.3
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_freebsd_target.rb

  # OpenBSD
  - name: openbsd-6
    driver:
      box: generic/openbsd6
      provision: true
      vagrantfiles:
        - tests/vagrant/vagrant_openbsd_target.rb


# Define playbook
suites:
  - name: default
    provisioner:
      name: ansible_playbook
      playbook: tests/test.yml
