---
# tasks file for ansible-role-bind

- name: Include OS specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install bind server
  include_tasks: "packages/setup-{{ ansible_system }}.yml"
