---
# Tasks file for install bind daemon on Linux system

- name: Update apt cache on Debian Family os
  apt:
    update_cache: yes
  changed_when: false
  when: ansible_os_family == "Debian"

- name: Update emerge cache on Gentoo
  shell: emerge-webrsync
  changed_when: false
  when: ansible_os_family == "Gentoo"

- name: Install bind package
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ bind_packages }}"
